# Generated by Django 2.2 on 2022-01-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_email_html_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='html_file',
            field=models.CharField(max_length=5000),
        ),
    ]
